import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/store/StoreProvider";
import CustomLogin from "@/components/CustomLogin";
import DrawerMenu from "@/components/DrawerMenu";
import NavLink from "@/components/NavLink";
import Image from "next/image";
import SpotifyLogo from "@/components/SpotifyLogo";
import ScrollToTopButton from "@/components/ScrollToTopButton";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Next Album",
	description: "Generated by create next app",
};

function NavLinks() {
	return (
		<>
			<NavLink href={"/"}>Search</NavLink>
			<NavLink href={"/followed-artists"}>Your artists</NavLink>
			<NavLink href={"/latest-releases"}>Latest releases</NavLink>
			<NavLink href={"/settings"}>Settings</NavLink>
		</>
	);
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased text-fg`}
			>
				<StoreProvider>
					<header className="flex flex-col justify-between static pt-4 top-0 right-0 left-0 bg-dark">
						<div className="flex items-center justify-between">
							<div className="flex items-center gap-8">
								
								<CustomLogin />	
							</div>

							<nav className="flex gap-2 flex-1 max-w-100 text-fg justify-end md:mr-4">
								<div className="hidden md:flex flex-1 gap-8 justify-end">
									<NavLinks />
								</div>

								<DrawerMenu className="md:hidden">
									<NavLinks />
								</DrawerMenu>
							</nav>
						</div>
						<hr className="bg-fg mt-3 h-0.5" />
					</header>

					{children}
					<ScrollToTopButton />
				</StoreProvider>
			</body>
		</html>
	);
}
