import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/store/StoreProvider";
import CustomLogin from "@/components/CustomLogin";
import DrawerMenu from "@/components/DrawerMenu";
import NavLink from "@/components/NavLink";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Next Album",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<StoreProvider>
					<header className="flex items-center justify-between">
						<CustomLogin />
						<nav className="flex gap-2 text-fg items-center md:mr-4">
							<DrawerMenu>
								<NavLink href={'/'}>Search</NavLink>
								<NavLink href={'/followed-artists'}>Your artists</NavLink>
							</DrawerMenu>
						</nav>
					</header>
					<hr className="bg-fg mt-3 h-0.5" />

					{children}
				</StoreProvider>
			</body>
		</html>
	);
}
